# Scripting for Bioinformatics

## Lab 03 - R

### Ejercicio 1

Dada una cadena _s_ completa la función siguiente para que todas las ocurrencias del primer caracter de la cadena _s_ se sustituyan por un `*`, excepto la primera ocurrencia misma. P.ej. `babble` resulta en `ba**le`

Puedes usar la función `substr` para extraer uno o varios caracteres de una cadena, y la función `gsub` para reemplazar caracteres. Recuerda que la función `nchar` devuelve el número de caracteres de una cadena.

Usa en una celda cualquiera

    ?substr
    
para obtener ayuda de la función `substr` o de una función cualquiera de R.

Por ejemplo, ejecuta la celda siguiente.

In [ ]:
?substr

In [ ]:
fix_start <- function(s) {
    # ---- tu codigo aqui ----
    r <- NULL
    # ------------------------
    return (r)
}


In [ ]:
fix_start("babble") == "ba**le"
fix_start("aardvark") == "a*rdv*rk"
fix_start("google") == "goo*le"
fix_start("donut")=="donut"

### Ejercicio 2

Dada una cadena _s_ completa la función siguiente para que:

1. encuentre la primera ocurrencia de la subcadena `not`  y la subcadena `bad`
2. si `not` aparece antes que `bad` reemplace toda la subcadena `not .. bad` con `good`
3. devuelva la cadena resultante

p.ej `This dinner is not that bad!` resulta en `This dinner is good!`

puedes usar la función R `gsub` de nuevo si quieres.

In [ ]:
not_bad <- function(s) {
    # ---- tu codigo aqui ----
    r <- NULL
    # ------------------------
    return (r)
}


In [ ]:
not_bad("This dinner is not that bad!")=='This dinner is good!'
not_bad('This tea is not hot') == 'This tea is not hot'
not_bad("It's bad yet not") == "It's bad yet not"
not_bad('Make me not so bad') == 'Make me good'

### Ejercicio 3

Completa la función siguiente para que dado un entero `n` y un caracter `c` (una cadena de longitud 1) devuelva un vector con `n` caracteres en orden alfabético empezando desde `c`. Si `n` desde `c` sobrepasa el final del alfabeto ha de seguir desde el principio. Si `n` es negativo o `c` es un caracter en mayúscula o no es una letra la función ha de devolver un vector vacío.

El siguiente código crea un vector vacío del tipo necesario:

     r <- character()

por ejemplo <br/>`lalpha (7, 'w')` resulta en `['w', 'x', 'y', 'z', 'a', 'b', 'c']`


In [ ]:
lalpha <- function(n,c) {
    a <- "abcdefghijklmnopqrstuvwxyz"
    # ---- tu codigo aqui ----
    r <- NULL
    # ------------------------
    return (r)
}

In [ ]:
all(lalpha (7, 'w') == c('w', 'x', 'y', 'z', 'a', 'b', 'c'))
all(lalpha(5,'a') == c('a', 'b', 'c', 'd', 'e'))
all(lalpha(2,'z') == c('z', 'a'))
length(lalpha(20,'-')) == 0
length(lalpha(-1,'x')) == 0


### Ejercicio 4
Completa la función `svm` para que devuelva una matriz de tamaño $n\_rows \times n\_cols$ con todos los elementos igual a $value$ de tipo `double`. Sugerencia, usa la función `matrix` con tres argumentos (como en las Notas)

_Ejemplo de ejecución_


    svm(n_rows=3, n_cols=4, value=5)
    
    
_Resultado_


    [[ 5  5  5  5]
     [ 5  5  5  5]
     [ 5  5  5  5]]

In [ ]:
svm <- function(n_rows, n_cols, value) {
    # ---- tu codigo aqui ----
    r <- NULL
    # ------------------------
    return (r)
}

In [ ]:
r = svm (2,5,3);  all(c(dim(r)==c(2,5), mean(r)==3,  sd(r)==0))
r = svm (3,1,31); all(c(dim(r)==c(3,1), mean(r)==31, sd(r)==0))
r = svm (1,5,2);  all(c(dim(r)==c(1,5), mean(r)==2,  sd(r)==0))
r = svm (2,2,-3); all(c(dim(r)==c(2,2), mean(r)==-3, sd(r)==0))

### Ejercicio 5

Dadas dos matrices de igual tamaño, $A \in \mathbb{R}^{m\times n}$ y $B \in \mathbb{R}^{m\times n}$ en la que cada línea de cada matriz representa un vector. Cada matriz tiene por tanto $m$ vectores de $n$ elementos. 

Denominamos los vectores de $A$ como $a^{(0)}$, $a^{(1)}$, $... a^{(m-1)}$ y los de $B$ como $b^{(0)}$, $b^{(1)}$, $... b^{(m-1)}$ 

Dados dos vectores $a^{(k)}$, $b^{(k)}$ la diferencia cuadrada media entre los elementos de los dos vectores viene dada por:

$$msd(a^{(k)}, b^{(k)}) = \frac{1}{n} \sum_{i=0}^{n} (a_{i}^{(k)} - a_{i}^{(k)})^2$$

donde $a_{i}^{(k)}$ es el elemento $i$ del vector $a^{(k)}$

completa la función `mmsd` para que, dadas dos matrices, devuelva una lista con la diferencia cuadrada media entre vectores correspondientes en ambas matrices. Es decir

$$mmsd(A,B)=[msd(a^{(0)}, b^{(0)}), msd(a^{(1)}, b^{(1)}),..., msd(a^{(m-1)}, b^{(m-1)})]$$

p.ej.

    A = np.array([[1,2,5],[3,4,1]])
    B = np.array([[0,3,0],[4,6,2]])
    mmsd(A,B)
    
    > array([ 9.,  2.])

In [ ]:
mmsd <- function(A,B){
    # ---- tu codigo aqui ----
    r <- NULL
    # ------------------------
    return (r)
}

In [ ]:
all.equal(mmsd(matrix(c(1,2,5,3,4,1), 2,3, byrow=TRUE), matrix(c(0,3,0,4,6,2),2,3,byrow=TRUE) ), c(9,2))
all.equal(mmsd(matrix(c(1,2,5,3,4,1,6,-1,2), 3,3, byrow=TRUE), matrix(c(0,3,1,4,1,2,2.3,-3,9.2), 3,3, byrow=TRUE)),
          c(6, 3.66666666666667, 23.1766666666667))            

### Ejercicio 6

Completa la función para que, dados dos vectores , devuelva un vector con todos los elementos de los dos vectores iniciales ordenados.


P.ej.:

    a <- c(1, 7, 8, 2, 7)
    b <- c(5, 8, 2)

    mergesort(a,b)
    > 1, 2, 2, 5, 7, 7, 8, 8

In [ ]:
mergesort <- function(a,b) {
    # ---- tu codigo aqui ----
    r <- NULL
    # ------------------------
    return (r)
}


In [ ]:
all.equal(mergesort(c(4,2,4,3,3),c(9,6,7)), c(2, 3, 3, 4, 4, 6, 7, 9) ) 
all.equal(mergesort(c(7,3), c(5,4,0,1)), c(0,1,3,4,5,7))

### Ejercicio 7

dado un vector `keys` de `n` cadenas (_strings_) y un vector `values` de `n` números, completa la función siguiente para que devuelva un vector con los $values$ en el cual los nombres de cada elemento corresponden al vector de cadenas.

Si el vector `values` tiene menos elementos que el vector `keys`, las `keys` correspondientes a los valores faltantes se asociarán a `NA`.

P.ej:

    mdict (["uno", "dos", "tres"], [10,20])
    > {'dos': 20, 'tres': None, 'uno': 10})

In [ ]:
mdict <- function(keys, values) {
    # ---- tu codigo aqui ----
    r <- NULL
    # ------------------------
    return (r)
}

In [ ]:
all.equal(mdict(c("uno", "dos", "tres"), c(10,20,30)) , c(uno=10, dos=20, tres=30))
all.equal(mdict(c("uno", "dos", "tres"), c(10,20)) , c(uno=10, dos=20, tres=NA))
all.equal(mdict(c("uno", "dos", "tres"), c(10,20, 30, 40)) , c(uno=10, dos=20, tres=30))

** LOS SIGUIENTES EJERCIOS SE REFIEREN AL SIGUIENTE `DataFrame` **

In [1]:
d <- read.csv("data/facturas.csv")
head(d)

fecha factura pais importe
1 7/26/2015    2242   CZ 1064.63
2 11/9/2014    2482   PL 1019.43
3 10/7/2015    1403   MA 1943.74
4 5/19/2015    2503   FR  212.74
5 6/20/2015    1440   FR  515.45
6  1/6/2015    1649   TN  789.68

### Ejercicio 8

Obtén un vector en el cual cada elementoes el número de veces que un país aparece en la columna `pais` y las etiquetas de la lista son los códigos del pais. 

Guarda el valor en la variable `cn`

In [ ]:
cn = numeric()

# ---- tu codigo aqui ----

In [ ]:
cn["AR"]==3
cn["CN"]==32
cn["BR"]==9
cn["ID"]==32
cn["RU"]==15
sum(cn)==200
length(unique(substr(names(cn), 1,1))) == 23

### Ejercicio 9

Obtén un vector con el número de veces que cada mes aparece en la columna `fecha`. Las etiquetas han de ser los números enteros del 1 al 12 (no como _strings_).

Recomendaciones:

- Usa `as.character(d$fecha)` para obtener la columna fecha como una lista de strings.

- Usa la función `strsplit` para partir una cadena por un caracter separado.

- En una lista de listas, usa `sapply(s, function(x) x[1])` para extraer el primer elemento de cada lista.


In [ ]:
r <- numeric()

# ---- tu codigo aqui ----

In [ ]:
r[names(r)==10] == 21
r[names(r)==11] == 15
r[names(r)==12] == 19
sum(r) == 200