# Scripting for Bioinformatics

## Lab 02 - Python


### Ejercicio 1

Dada una cadena _s_ completa la función siguiente para que todas las ocurrencias del primer caracter de la cadena _s_ se sustituyan por un `*`, excepto la primera ocurrencia misma. P.ej. `babble` resulta en `ba**le`

Mira la documentación de la clase _String_ [aquí](https://docs.python.org/2/library/string.html), puedes usar si quieres el método `s.replace(str1, str2)`


In [ ]:
def fix_start(s):
    # ---- tu codigo aqui -----
    r = None
    # ---- tu codigo aqui -----
    return r

In [ ]:
%run code/testing.py
test(fix_start("bubble"),"bu**le")
test(fix_start("aardvark"),"a*rdv*rk")
test(fix_start("google"),"goo*le")
test(fix_start("donut"),"donut");

### Ejercicio 2

Dada una cadena _s_ completa la función siguiente para que:

1. encuentre la primera ocurrencia de la subcadena `not`  y la subcadena `bad`
2. si `not` aparece antes que `bad` reemplace toda la subcadena `not .. bad` con `good`
3. devuelva la cadena resultante

p.ej `This dinener is not that bad!` resulta en `This dinner is good!`


In [ ]:
def not_bad(s):
    # ---- tu codigo aqui -----
    r = None
    # ---- tu codigo aqui -----
    return r

In [ ]:
%run code/testing.py
test(not_bad("This dinner is not that bad!"), 'This dinner is good!')
test(not_bad('This tea is not hot'), 'This tea is not hot')
test(not_bad("It's bad yet not"), "It's bad yet not")
test(not_bad('Make me not so bad'), 'Make me good');

### Ejercicio 3

Completa la función siguiente para que dado un entero `n` y un caracter `c` (una cadena de longitud 1) devuelva una lista con `n` caracteres en orden alfabético empezando desde `c`. Si `n` desde `c` sobrepasa el final del alfabeto ha de seguir desde el principio. Si `n` es negativo o `c` es un caracter en mayúscula o no es una letra la función ha de devolver una lista vacía.

por ejemplo <br/>`lalpha (7, 'w')` resulta en `['w', 'x', 'y', 'z', 'a', 'b', 'c']`


In [ ]:
def lalpha(n, c):
    alphabet = "abcdefghijklmnopqrstuvwxyz"
    # --- tu codigo aqui ----
    r = None
    # ------------------------
    return r
    

In [ ]:
%run code/testing.py
test(lalpha (7, 'w'), ['w', 'x', 'y', 'z', 'a', 'b', 'c'])
test(lalpha(5,'a'), ['a', 'b', 'c', 'd', 'e'])
test(lalpha(2,'z'), ['z', 'a'])
test(lalpha(20,'-'), [])
test(lalpha(-1,'x'), []);

### Ejercicio 4
Completa la función `svm` para que devuelva una matriz (array de `numpy`) de tamaño $n\_rows \times n\_cols$ con todos los elementos igual a $value$ de tipo `double`. Sugerencia, usa la función `numpy.ones` [[ref](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)]

_Ejemplo de ejecución_


    svm(n_rows=3, n_cols=4, value=5)
    
    
_Resultado_


    [[ 5.  5.  5.  5.]
     [ 5.  5.  5.  5.]
     [ 5.  5.  5.  5.]]

In [ ]:
import numpy as np

def svm(n_rows, n_cols, value):

    # ---- tu codigo aqui -----
    r = np.array([])
    # ---- tu codigo aqui -----

    return r

In [ ]:
%run code/testing.py
r = svm (2,5,3); test((r.shape, np.mean(r), np.std(r)), ((2,5), 3.0, 0.0))
r = svm (3,1,31); test((r.shape, np.mean(r), np.std(r)), ((3,1), 31.0, 0.0))
r = svm (1,5,2); test((r.shape, np.mean(r), np.std(r)), ((1,5), 2.0, 0.0))
r = svm (2,2,-3); test((r.shape, np.mean(r), np.std(r)), ((2,2), -3.0, 0.0));

### Ejercicio 5

Dadas dos matrices de igual tamaño, $A \in \mathbb{R}^{m\times n}$ y $B \in \mathbb{R}^{m\times n}$ en la que cada línea de cada matriz representa un vector. Cada matriz tiene por tanto $m$ vectores de $n$ elementos. 

Denominamos los vectores de $A$ como $a^{(0)}$, $a^{(1)}$, $... a^{(m-1)}$ y los de $B$ como $b^{(0)}$, $b^{(1)}$, $... b^{(m-1)}$ 

Dados dos vectores $a^{(k)}$, $b^{(k)}$ la diferencia cuadrada media entre los elementos de los dos vectores viene dada por:

$$msd(a^{(k)}, b^{(k)}) = \frac{1}{n} \sum_{i=0}^{n} (a_{i}^{(k)} - a_{i}^{(k)})^2$$

donde $a_{i}^{(k)}$ es el elemento $i$ del vector $a^{(k)}$

completa la función `mmsd` para que, dadas dos matrices (arrays de `numpy`), devuelva una lista con la diferencia cuadrada media entre vectores correspondientes en ambas matrices. Es decir

$$mmsd(A,B)=[msd(a^{(0)}, b^{(0)}), msd(a^{(1)}, b^{(1)}),..., msd(a^{(m-1)}, b^{(m-1)})]$$

p.ej.

    A = np.array([[1,2,5],[3,4,1]])
    B = np.array([[0,3,0],[4,6,2]])
    mmsd(A,B)
    
    > array([ 9.,  2.])
    


In [ ]:
def mmsd(A,B):
    # ---- tu codigo aqui -----
    result = None
    # ---- tu codigo aqui -----
    return result

In [ ]:
%run code/testing.py
test(mmsd( np.array([[1,2,5],[3,4,1]]), np.array([[0,3,0],[4,6,2]])) , 
     np.array([ 9.,  2.]))
test(mmsd(np.array([[1,2,5],[3,4,1], [6,-1,2]]), np.array([[0,3,1],[4,1,2], [2.3,-3,9.2]])),
     np.array([  6.        ,   3.66666667,  23.17666667]));

### Ejercicio 6

Completa la función para que, dados dos vectores (arrays `numpy` de una sola dimensión), devuelva un vector con todos los elementos de los dos vectores iniciales ordenados.

Si alguno de los dos vectores no son un array `numpy` o no son un vector (no tienen una sóla dimensión), la función ha de devolver un array `numpy` vacío.

Puedes usar la función [`numpy.hstack`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html) para unir dos vectores.

P.ej.:

    a = np.array([1, 7, 8, 2, 7])
    b = np.array([5, 8, 2])

    mergesort(a,b)
    > array([1, 2, 2, 5, 7, 7, 8, 8])


In [ ]:
def mergesort(a,b):
    # ---- tu codigo aqui -----
    r = None
    # ---- tu codigo aqui -----
    return r

In [ ]:
%run code/testing.py
test(mergesort(np.array([ 4.,  2.,  4.,  3.,  3.]), np.array([9, 6, 7])), 
     np.array([ 2.,  3.,  3.,  4.,  4.,  6.,  7.,  9.]) ) 

test(mergesort(np.array([7, 3]), np.array([5, 4, 0, 1])),
     np.array([0, 1, 3, 4, 5, 7]));

### Ejercicio 7

dada una lista de `n` cadenas (_strings_) y una lista cd `n` objectos (cualquiera) de Python, completa la función siguiente para que devuelva un diccionario de Python en donde cada cadena es la clave del objeto correspondiente en ambas listas.

Si algún objeto de la lista `keys` no es una cadena, debe de ignorarse el valor correspondiente de la lista `values`.

Si la lista `values` tiene menos elementos que la lista `keys`, las `keys` correspondientes a los valores faltantes se asociarán a `None`.

P.ej:

    mdict (["uno", "dos", "tres"], [10,20])
    > {'dos': 20, 'tres': None, 'uno': 10})


In [ ]:
def mdict(keys, values):
    
    # ---- tu codigo aqui -----
    r = None
    # ---- tu codigo aqui -----
            
    return r
    

In [ ]:
%run code/testing.py
test (mdict (["uno", "dos", "tres"], [10,20,30]),  {'dos': 20, 'tres': 30, 'uno': 10})
test (mdict (["uno", "dos", "tres"], [10,20]), {'dos': 20, 'tres': None, 'uno': 10})
test (mdict (["uno", 2, "tres"], [10,20]),{'tres': None, 'uno': 10} )
test (mdict (["uno", 2, "tres"], [10,20,30]), {'tres': 30, 'uno': 10});

**LOS SIGUIENTES EJERCIOS SE REFIEREN AL SIGUIENTE `DataFrame` **

In [2]:
import pandas as pd
d = pd.read_csv("data/facturas.csv")
print d.shape
d.head(n=10)

(200, 4)


fecha  factura pais  importe
0  7/26/2015     2242   CZ  1064.63
1  11/9/2014     2482   PL  1019.43
2  10/7/2015     1403   MA  1943.74
3  5/19/2015     2503   FR   212.74
4  6/20/2015     1440   FR   515.45
5   1/6/2015     1649   TN   789.68
6  4/23/2015     2973   NO  1141.43
7  5/27/2015     2647   ID   362.60
8  1/16/2015     2040   ID  1777.71
9   8/8/2015     2631   CN   804.76

### Ejercicio 8

Obtén un diccionario en el cual cada clave es un código de país y cada valor es el número de veces que dicho país aparece en la columna `pais`.

In [ ]:
pais_count = {}
# ---- tu codigo aqui -----
# ---- el resultado ha de estar en la variable pais_count

In [ ]:
%run code/testing.py
import hashlib

test(np.sum(pais_count.values()), 200)
test(pais_count["AR"],3)
test(pais_count["CN"],32)
test(pais_count["BR"],9)
test(hashlib.md5("".join(pais_count.keys())).hexdigest(), 'f13331642cf80773b74c8eac7617f4ba')
test(hashlib.md5("".join([str(i) for i in pais_count.values()])).hexdigest(), '08a2e7fb0a777a36010cfc6d2138c821');

### Ejercicio 9

Obtén un diccionario con el número de veces que cada mes aparece en la columna `fecha`. Las `keys` ha de ser los números enteros del 1 al 12 (no como _strings_).

Tendrás que usar la función split para obtener cada componente de la fecha.

In [ ]:
month_count = {}

# ---- tu codigo aqui -----
# ---- el resultado ha de estar en la variable month_count

In [ ]:
%run code/testing.py
test(np.sum([i for i in month_count.values()]), 200)
test(month_count[10], 21)
test(month_count[11], 15)
test(month_count[12], 19)
test(hashlib.md5(str(month_count)).hexdigest(),'731ffa53ea48d8a28ccc7a8e8cb8fa8d' );

### Ejercicio 10

Exporta este, Notebook a:

1. PDF, e incluye el PDF del mismo en tu entrega
- Python (`.py`), ejecuta desde la linea de comando el `.py` generado mediante:

       > ipython Lab\ 02\ -\ Python.py
     
  e incluye en tu entrega un pantallazo en JPG de la consola resultante

- Como presentación, usando el `Cell toolbar: slideshow` y estableciendo el tipo de `Slide` para cada celda. En el slideshow resultante ha de haber al menos un slide de cada tipo `Slide`, `Subslide` y `Fragment`. Desde la linea de comando en la máquina virtual ejecuta:

      > jupyter nbconvert --to slides --post serve --ServePostProcessor.ip='*' --ServePostProcessor.open_in_browser=False --ServePostProcessor.reveal_cdn=http://localhost:8000/reveal.js Lab\ 02\ -\ Python.ipynb
      
  esto abre un pequeño servidor web para tu presentación y la puedes abrir desde el nevegador de tu máquina física en 
  
       http://localhost:8000
       
  incluye en tu entrega un pantallazo de tu navegador con el slideshow según muestra algún ejercicio resuelto por ti.
  
- Finalmente, una vez que tu entrega esté en Dropbox, obtén un URL para compartirlo a través de [nbviewer](https://nbviewer.jupyter.org/) y entrega un fichero `Lab 02 - Python - nbviewer.url` que contenga dicho URL para poder abrirlo directamente desde cualquier navegador en modo sólo lectura.

En resumen, tu entrega ha de contener:

- el fichero `Lab 02 - Python.ipynb` con este notebook completado.
- el fichero `Lab 02 - Python.pdf` con su versión en PDF.
- el fichero `Lab 02 - Python - ejecucionpy.jpg` con el pantallazo de la ejecución por línea de consola.
- el fichero `Lab 02 - Python - slideshow.jpg` con el pantallazo de una página del slideshow en tu browser.
- le fichero `Lab 02 - Python - nbviewer.url` con el URL del nbviewer